import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

import { HomePage } from '../src/components/home/home-page';

export default function Home({ data }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Events app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>

      
      <nav>
        <img />
        <a href='/' >Home</a>
        <a href='/events' >Events</a>
        <a href='/about-us' >About us</a>
      </nav>
      </header>
      <main className={styles.main}>

      </main>
      <footer className={styles.footer}>
        <p> 2022 time to code</p>
            <HomePage data={data} />
    </div>
  );
}

/* export async function getServerSideProps() {
*  const { events_categories } = await import('/data/data.json');
*  return {
*    props: {
*      data: events_categories,
*    },
* };
* }
*/
31:06